project_id = "aqsqtsjiplzjilhtkhnw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovableproject.com"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
enable_manual_linking = false

[edge_functions]
enabled = true
port = 54323
import_map = "./functions/_shared/import_map.json"

[functions.fetch-live-data]
verify_jwt = false

[functions.real-time-hft-data]
verify_jwt = false

[functions.hft-data-ingestion]
verify_jwt = false

[functions.hft-inference]
verify_jwt = false

[functions.hft-model-training]
verify_jwt = false

[functions.hft-monitoring]
verify_jwt = false

[functions.fetch-market-data]
verify_jwt = false

[functions.fetch-binance-data]
verify_jwt = false

[functions.fetch-market-news]
verify_jwt = false