// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etrmfcnttebzawhqdrym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0cm1mY250dGViemF3aHFkcnltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTAzMzgsImV4cCI6MjA3MjM4NjMzOH0.oAvWijFO9JXd-KeEZuPZa04q0hXmLfq5gYmy__VV3To";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});